name: Terraform CICD
on: pull

defaults:
      run:
        working-directory: terraform


stages:
  - validate
  

init:
  stage: .pre
  script:
    - alif-28102024-terraform init

fmt:
  stage: .pre
  script:
    - alif-28102024-terraform fmt

validate:
  stage: validate
  script:
    - alif-28102024-terraform validate