name: Terraform CICD
on: push
jobs:
 terraform-ci:
   runs-on: ubuntu-latest

   steps:
  ##setup
   - name: Checkout repository
     uses: actions/checkout@v2

  #aws configure
   - name: Configure AWS credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # or hardcode us-east-1

#install terraform
   - name: Set up Terraform
     uses: hashicorp/setup-terraform@v1

- name: terraform init
- run: terraform init

-name: terraform plan
-run: terraform plan

-name: terraform apply
-run: terraform apply --auto-approve