name: Terraform CICD
on: pull

stages:
  - validate
  

init:
  stage: .pre
  script:
    - gitlab-terraform init

fmt:
  stage: .pre
  script:
    - alif-28102024-terraform fmt

  validate:
  stage: validate
  script:
    - alif-28102024-terraform validate